### ISSUE TITLE
Feasibility of adding more buttons + profile switching

### ISSUE THREAD

**Issue by ItaloKnox** [sb-ocr/ocreeb-12#2]
Hello! I got your video recommended on YouTube and the bonus midi capabilities really sold me to build one myself. I have a decent grasp of Python, got a 3D printer coming and some Arduino experience. Just a few days ago, I started using micropython on a couple ESP8266 boards, so I'm still figuring out how to handle the interfacing between Python and a board.

If possible, I hope you can help me squash a few questions before I can start the build:

1- Adafruit products are hard to come by in Brazil, so I decided to import a few generic RP2040 boards from AliExpress, since the ESP8266 isn't compatible with Circuitpython. [These](https://circuitpython.org/board/vcc_gnd_yd_rp2040/), and the 16mb model to be exact. Other than the bigger footprint of the board, double-checking the pins and the adjustments necessary to the PCB, is there anything else I should be on the lookout?

2- Like the title said, I want to expand the board to add more buttons. Maybe a 4x4 or 4x5 grid. I'm having some trouble understanding the switch matrix in the code, the macros rows are self-explanatory (I believe I just need to add the new buttons to each row), but I'm having trouble figuring out if I need to set up more pins for the extra buttons.

3- Third and final, the reason why I need more buttons is that I plan on using these to facilitate my Blender workflow and DAW (both with midi and keyboard shortcuts - but not at the same time). Of course, both software don't share the same shortcuts, and using the pad outside of them would also be pretty much useless. How feasible would it be to set up profile switching to a new extra button and then change all macros based on that?

I'm looking forward to seeing more videos from you on YouTube. Best of luck!

**Comment by sb-ocr** [comment]
Thank you for checking out the project.

1- As you said the footprint of the board you chose isn't compatible with this PCB. So if you're going to design a new one for it to fit, it should be fine. The other thing is the castellated pads, this board doesn't have them and to solder it directly to a PCB you would need to use use some shortened headers for example.

2- Yes you need more pins to add more switches in your matrix but usually it's in a grid configuration. If we take the example you provided 4 x 5. You can setup this as 4 columns and 5 rows (or the other way around) for a total of 9 pins to detect 20 keys, the diodes will prevents the current to go backwards (and causing ghost keystrokes). After you initialize the keyboard class in KMK you supply the row pins, the columns pins and the diodes orientation. The matrix scanner isn't the only one available in KMK you can checkout [this part](https://github.com/KMKfw/kmk_firmware/blob/master/docs/en/scanners.md) of the documentation for more options on how to add other hardware.

3- Yes, this concept is called [Layers](https://github.com/KMKfw/kmk_firmware/blob/master/docs/en/layers.md) in keyboard firmware. You can jump between them in different ways: Toggle, Momentary hold or even [Tap dance](https://github.com/KMKfw/kmk_firmware/blob/master/docs/en/tapdance.md) (that's what I used to toggle the midi layer in this project)

I hope this answered all your questions. Best of luck!
