### ISSUE TITLE
Library Files

### ISSUE THREAD

**Issue by RichardTHF** [sb-ocr/ocreeb-12#3]
Hi, 

Do you the lbr Library Files for the KB2040 and KB2040 MacroPad? Trying to modify the PCB for the more common and cheap RP2040-Zero? I can only find their board and schematic on the Adafruit GitHub and Eagle won't me modify the PCB without them. 

![image](https://user-images.githubusercontent.com/5789676/198198725-8e8e11ac-69c0-492b-a3dd-44544c7623bf.png)

:)

**Comment by sb-ocr** [comment]
Hi,
I just exported the libraries used in the project and added the file to the PCB folder.
Let me know if it works for you.
