### ISSUE TITLE
WS2812B Neopixel doesn't work

### ISSUE THREAD

**Issue by GeoffreyOlivier** [sb-ocr/ocreeb-12#7]
Hello, with my friend we have build two keyboard, but the neopixel doesn't work. 

There issue with keyboard azerty ? 

thanks

**Comment by sb-ocr** [comment]
No, it's probably the soldering of the Neopixels. Try to reflow them again

**Comment by inlag** [comment]
@GeoffreyOlivier 
I'm not sure if I can help, but I had the same problem.
In my case I needed to update the CircuitPython firmware from adafruit to version 8.2.6

**Comment by GeoffreyOlivier** [comment]
@inlag 
I didn't see your response.
I tried last version and the 8.2.6 and not working. I don't know why. 
thanks btw
